Release: RörLa Public Transport Step 1 (#65)
**Release notes:**

Buses move between bus stops according to time schedule.
Now hopefully without any bugs.

**Details:**
* fix: remove suffix on services (#58)

* sync main with develop (#59)

* fix: limit resources

* draft: Fix/filter stops (#50)

* Use single source for gtfs data

* feat: expose function for bus stops map

* WIP: merge gtfs data

* feat: filter trips based on date

* Update packages/simulator/index.js

* Update packages/simulator/lib/kommun.js

* Update packages/simulator/lib/vehicles/vehicle.js

* wip: filter on current date

* wip: writing tests for bus

Co-authored-by: Stefan Wallin <github@stefan-wallin.se>
Co-authored-by: Christian Landgren <christian@landgren.nu>

* Bus Stop times are now in order

* fix: don't crash if cache folder doesnt exist

* fix: use concatmap to get stop times in date order

* fix: use same stream when creating bus and internal busstops stream

* chore: comment out booking dispatch log for now

* chore: remove old commented code

* chore: set starthour to 6.4 to get closer to test case

* style: prettier

* chore: log output to test

* fix: make bus start at right time to right stop

Co-authored-by: Stefan Wallin <github@stefan-wallin.se>

* fix: remove bus duplicity with sharedReplay

* chore: slow down timemultipler to debug

* fix: handle last bus stop

* chore: investigate perf. issues with more buslines

* wip: solving performance problems

Co-authored-by: Stefan Wallin <github@stefan-wallin.se>

* style: prettier

* fix: set right Id on bus

* chore: comment osrm logs

* chore: improve logs in bus

* chore: move startHour

* chore: filter serviceDateTimes correctly

* fix: remove "cleanbookings" before socket
This was causing the hover to break

* fix: change back to throttleTime instead of buffer

* chore: cleanup

* style: prettier

* fix: group by tripId and not trip.id (which is undefined)

Co-authored-by: Stefan Wallin <github@stefan-wallin.se>
Co-authored-by: Mikael Gråborg <mikael.graborg@iteam.se>
Co-authored-by: Mikael Gråborg <graborg@Mikaels-MBP.lan>

* fix: use correct urls for prod and stage

Co-authored-by: Stefan Wallin <github@stefan-wallin.se>
Co-authored-by: Mikael Gråborg <mikael.graborg@iteam.se>
Co-authored-by: Mikael Gråborg <graborg@Mikaels-MBP.lan>

* Feat/regions (#62)

* only take one update per x ms per vehicle

* feat: put buses on region instead

* typo

* Fix TypeError

```
  *** ERROR "Route error" FetchError: request to https://osrm.iteamdev.io/route/v1/driving/22.347844,65.686238;22.347844,65.686238?steps=true&alternatives=false&overview=full&annotations=true failed, reason: getaddrinfo ENOTFOUND osrm.iteamdev.io
  OSRM fetch err FetchError: request to https://osrm.iteamdev.io/nearest/v1/driving/21.02216625611887,64.74634265953179 failed, reason: connect ETIMEDOUT 5.35.191.48:443
    at ClientRequest.<anonymous> (digital-twin/packages/simulator/node_modules/node-fetch/index.js:133:11)
    ...
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      type: 'system',
      errno: 'ETIMEDOUT',
      code: 'ETIMEDOUT'
    }
    digital-twin/packages/simulator/node_modules/rxjs/dist/cjs/internal/util/reportUnhandledError.js:13
       throw err;
       ^

    TypeError: Cannot read properties of undefined (reading 'waypoints')
      at digital-twin/packages/simulator/simulator/address.js:25:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Co-authored-by: Stefan Wallin <github@stefan-wallin.se>

* Feat/refactor experiments (#63)

* only take one update per x ms per vehicle

* feat: put buses on region instead

* typo

* chore: refactor code to use experiment as the base

* feat: refactor wait so it waits until a departure time instead of x ms with timeout

* fix: fix a few bugs

* Clean out unused imports

* Clean out unused imports

* Update GTFS data

* Bug reduction. 4 steps back, 3 steps forward

* feat: add final stop to buses

* fix: buses should start on time and continue after first stop

Co-authored-by: Stefan Wallin <github@stefan-wallin.se>
Co-authored-by: Mikael Gråborg <mikael.graborg@iteam.se>

* chore: ignore .envrc (#64)

Co-authored-by: Christian Landgren <christian@landgren.nu>
Co-authored-by: Mikael Gråborg <mikael.graborg@iteam.se>
Co-authored-by: Mikael Gråborg <graborg@Mikaels-MBP.lan>
Co-authored-by: Alexander Czigler <dev@ilix.se>